version: "3.9"
   
services:
    mongodb:
      image: mongo
      volumes:
        # - ./init-db:/docker-entrypoint-initdb.d
        # - ./data-db:/data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: mongoadmin
        MONGO_INITDB_DATABASE: django_mongodb_docker
      ports:
        - 27017:27017
    

    django_app:
        image: app
        restart: always
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
        - .:/django_mongodb_docker
        ports:
        - 8000:8000
        links:
        - mongodb
        depends_on:
        - migration

                        
    prometheus:
        image: prom/prometheus:latest
        volumes:
        - ./prometheus/:/etc/prometheus/
        - ./prometheus/data:/prometheus
        command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
        ports:
        - 9090:9090
        links:
        - cadvisor:cadvisor
        - alertmanager:alertmanager
        depends_on:
        - cadvisor
        networks:
        - app-tier
        restart: always

    grafana:
        image: grafana/grafana
        user: "472"
        depends_on:
          - prometheus
        ports:
          - 3001:3000
        volumes:
          - ./grafana/data:/var/lib/grafana
          - ./grafana/provisioning/:/etc/grafana/provisioning/
        env_file:
          - ./grafana/config.monitoring
        networks:
          - app-tier
          - grafana-tier
        restart: always
    
    redis:
      image: "redis:alpine"
      networks: 
         - app-tier
      ports:
        - "6379:6379"    
      